### ISSUE TITLE
Master build fails: TS2304: Cannot find name 'GBAIconEnhanced'.

### ISSUE THREAD

**Issue by aghoneim92** [aliceservices/alice#9]
After merging GBA with my latest changes, I get this error
